
SELECT ID_CLIENTE_TOPGROUP, DESCRIPCION_SUCURSAL FROM CABECERAS_VENTAS
WHERE ID_CLIENTE_TOPGROUP LIKE '%10538%'


/*  */

SELECT
    DESCRIPCION_SUCURSAL,
    FECHA_DE_DOCUMENTO,
    ID_DOCUMENTO_TRX,
    CANAL_DE_VENTA,
    ID_CLIENTE_TOPGROUP,
    ID_CLIENTE
FROM CABECERAS_VENTAS
WHERE FECHA_DE_DOCUMENTO = DATEADD(day, -1, CONVERT(date, GETDATE()))

-- (18280 rows)

SELECT
    DESCRIPCION_SUCURSAL,
    FECHA_DE_DOCUMENTO,
    ID_DOCUMENTO_TRX,
    CANAL_DE_VENTA,
    ID_CLIENTE_TOPGROUP,
    ID_CLIENTE
FROM CABECERAS_VENTAS

-- (1330550 rows)
/*  */
SELECT TOP 8000
    DESCRIPCION_SUCURSAL,
    FECHA_DE_DOCUMENTO,
    ID_DOCUMENTO_TRX,
    ID_CLIENTE_TOPGROUP
FROM (
    SELECT  
        DESCRIPCION_SUCURSAL,
        FECHA_DE_DOCUMENTO,
        ID_DOCUMENTO_TRX,
        ID_CLIENTE_TOPGROUP,
        ROW_NUMBER() OVER (PARTITION BY DESCRIPCION_SUCURSAL, ID_CLIENTE_TOPGROUP ORDER BY (SELECT NULL)) AS RowNum
    FROM CABECERAS_VENTAS
    WHERE FECHA_DE_DOCUMENTO = DATEADD(day, -1, CONVERT(date, GETDATE())) AND ID_CLIENTE_TOPGROUP IS NOT NULL
) AS TempTable
WHERE RowNum = 1
ORDER BY ID_CLIENTE_TOPGROUP ASC
-- (4790 rows) (sin duplicados)
/*  */
