/* query de la autom 'Contactos_Generales_Sync' que popula 'Contactos_Generales' */
SELECT
    acc.Id AS Id,
    acc.IsDeleted AS IsDeleted,
    acc.Name AS Name,
    acc.LastName AS LastName,
    acc.FirstName AS FirstName,
    acc.RecordTypeId AS RecordTypeId,
    acc.BillingStreet AS BillingStreet,
    acc.BillingCity AS BillingCity,
    acc.BillingState AS BillingState,
    acc.BillingPostalCode AS BillingPostalCode,
    acc.BillingCountry AS BillingCountry,
    acc.BillingAddress AS BillingAddress,
    acc.ShippingStreet AS ShippingStreet,
    acc.ShippingCity AS ShippingCity,
    acc.ShippingState AS ShippingState,
    acc.ShippingPostalCode AS ShippingPostalCode,
    acc.ShippingCountry AS ShippingCountry,
    acc.ShippingAddress AS ShippingAddress,
    acc.Phone AS Phone,
    acc.Industry AS Industry,
    acc.NumberOfEmployees AS NumberOfEmployees,
    acc.OwnerId AS OwnerId,
    acc.CreatedDate AS CreatedDate,
    acc.CreatedById AS CreatedById,
    acc.LastActivityDate AS LastActivityDate,
    acc.PersonContactId AS PersonContactId,
    acc.IsPersonAccount AS IsPersonAccount,
    acc.PersonMailingStreet AS PersonMailingStreet,
    acc.PersonMailingCity AS PersonMailingCity,
    acc.PersonMailingState AS PersonMailingState,
    acc.PersonMailingPostalCode AS PersonMailingPostalCode,
    acc.PersonMailingCountry AS PersonMailingCountry,
    acc.PersonMailingAddress AS PersonMailingAddress,
    acc.PersonMobilePhone AS PersonMobilePhone,
    acc.PersonHomePhone AS PersonHomePhone,
    acc.PersonOtherPhone AS PersonOtherPhone,
    acc.PersonAssistantPhone AS PersonAssistantPhone,
    acc.PersonEmail AS PersonEmail,
    acc.PersonTitle AS PersonTitle,
    acc.PersonDepartment AS PersonDepartment,
    acc.PersonLeadSource AS PersonLeadSource,
    acc.PersonBirthdate AS PersonBirthdate,
    acc.PersonEmailBouncedReason AS PersonEmailBouncedReason,
    acc.PersonEmailBouncedDate AS PersonEmailBouncedDate,
    acc.PersonIndividualId AS PersonIndividualId,
    acc.AccountSource AS AccountSource,
    acc.Razon_social__c AS Razon_social__c,
    acc.CUIT__c AS CUIT__c,
    acc.DNI__c AS DNI__c,
    acc.Rubro__c AS Rubro__c,
    acc.No_tiene_email__c AS No_tiene_email__c,
    acc.Cantidad_de_Empleados__c AS Cantidad_de_Empleados__c,
    acc.Activa__c AS Activa__c,
    SUC.Name as Sucursal__c,
    acc.Exenciones__c AS Exenciones__c,
    acc.Fecha_de_caducidad_de_exenciones__c AS Fecha_de_caducidad_de_exenciones__c,
    acc.Condicion_de_IVA__c AS Condicion_de_IVA__c,
    acc.Fecha_Ultima_Compra__c AS Fecha_Ultima_Compra__c,
    acc.Tipo_Registro_de_Cuenta__pc AS Tipo_Registro_de_Cuenta__pc,
    acc.Rubro__pc AS Rubro__pc,
    acc.Frecuencia__pc AS Frecuencia__pc,
    acc.Empleados_de_la_Compa_a__pc AS Empleados_de_la_Compa_a__pc,
    acc.et4ae5__HasOptedOutOfMobile__pc AS et4ae5__HasOptedOutOfMobile__pc,
    acc.et4ae5__Mobile_Country_Code__pc AS et4ae5__Mobile_Country_Code__pc,
    rt.Name AS Tipo_Cliente,
    acc.Id_Top_Group_texto__c as Id_Topgroup
    
FROM
    SFImport_Accounts_4 AS acc
INNER JOIN RecordType AS rt ON rt.Id = acc.RecordTypeId
LEFT JOIN Unsubscribed_Bounce_Held AS ubh ON ubh.EmailAddress = acc.PersonEmail
LEFT JOIN Unsubscribed_1895_1_BBDD_Maestra AS u1bm ON u1bm.Email = acc.PersonEmail
LEFT JOIN SFSucursal_Import_2 as SUC on SUC.id_top_group__c = (acc.Sucursal__c + '.0')
WHERE 
u1bm.Email IS NULL AND 
ubh.EmailAddress IS NULL AND
acc.IsPersonAccount = '1'